### ISSUE TITLE
move "INCLUDE2" directory to the "main" directory

### ISSUE THREAD

**Issue by rtagirov** [rtagirov/nessy#1]

**Comment by rtagirov** [comment]
we figured out yesterday that there is no need for that. I propose we change the purpose of the issue. the INCLUDE2 directory stays separate from the main source files of the code, however I'd prefer the name of this directory to be changed to "inc" in line with the 3-letter naming approach we adopted yesterday. Incidentally, I forgot to ask, are you fine with the 3-letter naming approach? If not I invite your opinion on that matter.

**Comment by Migelo** [comment]
You are correct, move the folder with `git mv` and close this issue with your comit.
Nah, 3-letter naming convention is fine for Linux (etc, opt, usr, mnt, bin...) so it should be fine for us as well.

**Comment by rtagirov** [comment]
okay. will do. we'll use more than 3 letters whenever there is no other way. I'll change the corresponding paths in the routines of the code as well.

**Comment by rtagirov** [comment]
I'll do that in the ic_nan_bug branch only because I intend it to be the master branch in the nearest future. the current master branch will be discarded once we verify that the fixed code runs on all relevant machines (mps & ic).

**Comment by Migelo** [comment]
Roger that!
