### ISSUE TITLE
Equivalent of 'lte' command

### ISSUE THREAD

**Issue by Migelo** [rtagirov/nessy#2]
In an older version of `hminus.exe` one would put `lte` in `fort.99` but that's changed in the new version. How can I do a 'lte' run of 'hminus' with this version?

**Comment by rtagirov** [comment]
you mean the version I sent you yesterday?

**Comment by rtagirov** [comment]
my guess would be "yes". in the version I sent you I changed it for some reason (that I can't recollect) to "lte_run". so in fort.99 with my version of the code you write "lte_run" instead of "lte". however you can change it back. it's the line 224 of hminus.for

**Comment by Migelo** [comment]
That is fine, `lte_run` it is, no need to change :) thanks!
